AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-typescript

  Sample SAM Template for hello-typescript
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/dist
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        UserPost:
          Type: Api
          Properties:
            Path: /user
            Method: post
        UserGet:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: get
        UsersGet:
          Type: Api
          Properties:
            Path: /user
            Method: get
        UserPut:
          Type: Api
          Properties:
            Path: /user
            Method: put
        UserDelete:
          Type: Api
          Properties:
            Path: /user
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserApi:
    Description: "API Gateway endpoint URL for Prod stage for User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/"
  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
  UserFunctionIamRole:
    Description: "Implicit IAM Role created for User function"
    Value: !GetAtt UserFunctionRole.Arn
